### ISSUE TITLE
How to get the pose.json?

### ISSUE THREAD

**Issue by lujiaxuan0520** [weleen/AGRL.pytorch#1]
I tried to train the model using the dataset ilids-vid, but received the error "No such file or directory: 'data\\ilids-vid\\pose.json'". It seems that the file "pose.json" is not in the dataset downloaded from the source. How can I get the pose.json of those datasets?

**Comment by weleen** [comment]
Sorry, I will upload the .json files and model files ASAP.

**Comment by weleen** [comment]
@lujiaxuan0520, hi, we have updated the links for `pose.json` and model weights.

**Comment by lujiaxuan0520** [comment]
Okay, thanks.
