### ISSUE TITLE
代码中的超参和论文中略有不同，使用代码中的超参很难训到论文精度，请问有什么训练技巧吗

### ISSUE THREAD

**Issue by QLSong** [weleen/AGRL.pytorch#2]
使用代码中的参数在duke-video上达到了论文精度，在mars上map低于论文四个点，论文中的实验是以那个参数为准？求教，谢谢

**Comment by weleen** [comment]
@QLSong 您好，以代码中为准，我稍后把日志文件发上来，你可以对照一下。

**Comment by weleen** [comment]
[log_train.txt](https://gist.github.com/weleen/2bf8cf9e01b7e8622caa505e1837ceff)

**Comment by QLSong** [comment]
@weleen 已经找到问题，谢谢
