### ISSUE TITLE
splits_prid2011.json文件怎么获得的啊？

### ISSUE THREAD

**Issue by wangyingquan** [weleen/AGRL.pytorch#3]
你好！ 
    请问下，prid2011中的splits_prid2011.json文件从哪里下载的啊？我从你提供的链接上下不到，可以提供一下文件吗？

**Comment by weleen** [comment]
@wangyingquan 
你好，splits_prid2011.json是iLIDS作者用于十折实验的文件，可以从[这里](http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/datasets/prid2011/splits_prid2011.json)下载到，[DATASETS.md](https://github.com/weleen/AGRL.pytorch/blob/master/DATASETS.md)也有对PRID2011和其他数据集的介绍。

**Comment by wangyingquan** [comment]
好的，谢谢。
