### ISSUE TITLE
self.poses = json.load(f)

### ISSUE THREAD

**Issue by 13121283123** [weleen/AGRL.pytorch#5]
对您的这篇文章很感兴趣，但是有一个地方一直有些疑惑，想请教一下您 self.poses = json.load(f)中的bodies中的joints是什么意思啊

**Comment by weleen** [comment]
@13121283123 你好，pose文件中的joints对应的是使用AlphaPose提取出的骨骼点坐标以及置信度，具体节点含义可以参考[AlphaPose Format](https://github.com/MVIG-SJTU/AlphaPose/blob/pytorch/doc/output.md)，我们用的是18个节点的设置。
